### ISSUE TITLE
Tutorials: Meta-Issue

### ISSUE THREAD

**Issue by alyakin314** [graspologic-org/graspologic#447]
If nobody minds, I decided to make a list of all tutorial that exist and don't yet, and mark which need to be updated/created. I was a little confused by the multitude of issues, and I have a feeling that I am not the only one. @bdpedigo , please feel free to edit this post as you like.

- Models
  - Random Graph Models
  - (Eventually merge with simulations.)
    - [ ] Needs to be modified; see #368 for more information on merging models and simulations.
- Simulations
  - Erdos-Renyi (ER) Model
  - Stochastic Block Model (SBM)
  - Random Dot Product Graph (RDPG) Model
  - Correlated Graph Pairs
  - Correlated Random Dot Product Graph (RDPG) Graph Pair
- Embedding
  - Adjacency Spectral Embed
  - Embedding Multiple Graphs (aka OMNI?)
  - MASE
    - [x] Needs to be created; see #244. Claimed by @pauladkisson.
  - Advanced tutorial: Omni vs. MASE.
    - [ ] Needs to be created; see #444. Claimed by @PerifanosPrometheus.
  - Advanced tutorial: ASE vs LSE vs N2V.
    -  [ ] Needs to be created; see #401 (needs a separate issue?)
- Inference
  - Latent Position Two-Graph Testing
  - Latent Distribution Two-Graph Testing
    - [x] Needs to be modified; see #177. Claimed by @kareef928.
- Plotting
  - Heatmap: Visualizing a Graph
  - Gridplot: Visualize Multiple Graphs
  - Pairplot: Visualizing High Dimensional Data
- Matching
  - Introduction to Graph Matching
  - Seeded Graph Matching (SGM)
- Subgraph
  - Signal Subgraph Estimators
    - [ ] Will be modified & other algorithms added; see #120, #150, #305 & #349. Claimed by @caseypw . 
- Clusterings
  - All of them
    - [x] Need to be created; see #333. Claimed by @caseypw.
- Align
  - All of them
    - [x] Need to be created; see #414. Claimed by @Jingyan230. (probably downstream from #419 )
- Currently Miscellaneous
  - Regularization, P2R.
    -  [ ] Needs to be created; see #401 (needs a separate issue?)
  - Central Limit Theorem
    -  [ ] Needs to be created; see #442 (probably downstream from #378 )
  - The Embedding, the Alignment, and The LatentDistributionTest.
    - [ ] Needs to be created; see #443 (probably downstream from Align and LDT tutorials)

**Comment by alyakin314** [comment]
Questions:
1. Is Models really that different from Simulations?
2. Do we want LSE & OMNI tutorials separate from the Advanced ones?

**Comment by caseypw** [comment]
The signal-subgraph estimators currently have a tutorial notebook, however I'm editing it at the moment and am also going to PR 3 more signal-subgraph algorithms with their associated tutorial notebooks.

Thank you for this helpful list @alyakin314 !

**Comment by alyakin314** [comment]
> The signal-subgraph estimators currently have a tutorial notebook, however I'm editing it at the moment and am also going to PR 3 more signal-subgraph algorithms with their associated tutorial notebooks.

oh, cool. i wasn't aware and didn't see an accompanying issue. is that #150 / #305 or something else?

**Comment by caseypw** [comment]
> > The signal-subgraph estimators currently have a tutorial notebook, however I'm editing it at the moment and am also going to PR 3 more signal-subgraph algorithms with their associated tutorial notebooks.
> 
> oh, cool. i wasn't aware and didn't see an accompanying issue. is that #150 / #305 or something else?

I will PR'ing for #150 as well as #120 , commit for #305 is located [here](https://github.com/neurodata/graspy/commit/85e523cf887af47a963e750b8e264749824923ca). I won't include #305 in the PR but it will still address it basically.

**Comment by PerifanosPrometheus** [comment]
Thank you @alyakin314 for the exhaustive list! Currently I would like to work on #444, I am waiting to see if other people are also interested and if not I will start working on it right away!

**Comment by bdpedigo** [comment]
appreciate the list, just a note though, I have been thinking a lot about separating tutorial-like stuff into a few different categories, namely 

- one category aimed at casual/intro user, just showing inputs/outputs/high level intuition for what is going on
- one category aimed at deeper understanding by showing math and simulations. this would take some of what we have in tutorials already but I'd also love for it to go deeper on some topics (ASE vs LSE, MASE vs OMNI, regularization of embeddings, all the nuances of LDT, etc.) 
- (possibly) one more applied category where we can show some example use on less trivial real data examples. Almost like a storybook showing some of this stuff used in practice.

So just wanted to point out that the structure of all of the stuff in @alyakin314's list above may change drastically if we do this

**Comment by loftusa** [comment]
this site is relevant here I think, particularly with respect to the above @bdpedigo comment: https://documentation.divio.com/tutorials/

**Comment by alyakin314** [comment]
i'll update the list some time very soon.
